#Ege Ozan Ozyedek
#21703374
#CS202

avlfreq: avlfreq.o main.o
	g++ avlfreq.o main.o -o avlfreq --std=c++11

main.o: main.cpp
	g++ -c main.cpp --std=c++11

avlfreq.o: avlfreq.cpp
	g++ -c avlfreq.cpp --std=c++11

clean:
	rm *.o avlfreq

